### PR TITLE
fixed sidebar ui/expansion

### LINKED ISSUE #207: [ui] static dock & set default theme to dark
- [ ] commnet out the toggle dark mode button as we don't have white for ready for this version yet and keep dark mode as default.
- [ ] add feedback and profile button to the static dock along with other three buttons.
- [ ] keep dock animation commented out for now.

### PR DESCRIPTION
**Pull request by joaorceschini**
- improved sidebar expansion logic
- removed framer motion
- fixed icons alignment
- fixed profile icon
- removed inline css
- removed unused commented lines

https://github.com/user-attachments/assets/4b315ee9-7d6e-4d3a-8522-631335678bce

### CODE REVIEW

File: apps/frontend/src/components/Sidebar.tsx [hunk 1]
```diff
@@ -97,33 +59,21 @@ const SidebarLink = ({
...
-
-  const { session } = useAuth()
-
   const { showModal } = useModal()
 
-  const [lastSpaceRoute, setLastSpaceRoute] = useState<string | null>(null)
-  const [isHovered, setIsHovered] = useState(false) // State for hover
-  const mouseY = useMotionValue(Infinity)
+  const [isExpanded, setIsExpanded] = useState(false)
+  const [holdIsExpanded, setHoldIsExpanded] = useState(false)
```
Comment (madhav-relish) [inline apps/frontend/src/components/Sidebar.tsx]: I don't think holdIsExpanded state is required here. You can use isExpanded only

File: apps/frontend/src/components/Sidebar.tsx [hunk 2]
```diff
@@ -97,33 +59,21 @@ const SidebarLink = ({
...
-    return null
-  }
-  // eslint-disable-next-line
   useEffect(() => {
-    if (pathname.startsWith("/space/")) {
-      setLastSpaceRoute(pathname)
-    }
-  }, [pathname])
+    setHoldIsExpanded(isExpanded)
+  }, [isExpanded])
```
Comment (madhav-relish) [inline apps/frontend/src/components/Sidebar.tsx]: This can be removed

File: apps/frontend/src/components/Sidebar.tsx [hunk 3]
```diff
@@ -147,22 +97,19 @@ const Sidebar: React.FC = () => {
...
-        onMouseLeave={() => {
-          mouseY.set(Infinity); 
-          setIsHovered(false);  
-        }}
-        onMouseEnter={() => setIsHovered(true)}  
-      >
+    <div
+      className={classNames(
+        "mx-4 my-auto flex select-none flex-col rounded-[30px] border border-border px-2 transition-all",
+        holdIsExpanded ? "py-8" : "pt-8 pb-2"
```
Comment (madhav-relish) [inline apps/frontend/src/components/Sidebar.tsx]: Instead of this you can use   const expandedClassName = isExpanded ? "py-8" : "pt-8 pb-2" and use expandedClassName whereever needed

File: apps/frontend/src/components/Sidebar.tsx [hunk 4]
```diff
@@ -180,181 +127,70 @@ const Sidebar: React.FC = () => {
...
-                stroke={pathname === "/settings/" ? "#000" : "#676767"}
-                strokeWidth="1.5"
-                strokeLinecap="round"
+        {holdIsExpanded ? (
```
Comment (madhav-relish) [inline apps/frontend/src/components/Sidebar.tsx]: You can use isExpanded here since holdIsExpanded holds the same value as isExpanded

File: apps/frontend/src/components/Sidebar.tsx (hunk 3 above)
Comment (madhav-relish) [reply apps/frontend/src/components/Sidebar.tsx]: Or just use  isExpanded ? "py-8" : "pt-8 pb-2"

File: apps/frontend/src/components/Sidebar.tsx (hunk 1 above)
Comment (joaorceschini) [reply apps/frontend/src/components/Sidebar.tsx]: you are right haha thank you

File: apps/frontend/src/components/Sidebar.tsx (hunk 4 above)
Comment (joaorceschini) [reply apps/frontend/src/components/Sidebar.tsx]: fixed! thanks

**Review by madhav-relish — APPROVED** [review]
