### PR TITLE
fix notes store w new backend changes

### LINKED ISSUE #226: fix notes store w new backend changes
- [ ] \~\~minor ui improvement such as replacing the stack icon with text button. see figma design for nore: \~\~[~~https://www.figma.com/design/VMVSHyLb3cofjSZwWkUZ9q/White-mode-initials?node-id=0-1&node-type=canvas&t=Y2xZWV2O587uC6ta-0~~](https://www.figma.com/design/VMVSHyLb3cofjSZwWkUZ9q/White-mode-initials?node-id=0-1&node-type=canvas&t=Y2xZWV2O587uC6ta-0)
- [ ] ~~when the notes page loads first time it shows loading in description area, instead create an untitled note when they land on notes page the pointer stays in title.~~
- [ ] ~~enable jump to description on enter from title ( now the title is expanding)~~
- [ ] ~~BUG: notes do not save immediately if i go to a different page and come back the note title is not there. I can only see description text.~~
- [ ] ~~BUG: if i go to a different page and come back to note page, each time it creates an untitled note.~~

- [ ] data are not being updated/saved in notes — apply changes as per backend
- [ ] Pointer issue in description, the pointer has to be manually placed to write
- [ ] Shift enter/ enter : does not work as they should: make enter to jump to description when on title, and in description shift+ enter to break line.

### PR DESCRIPTION
**Pull request by joaorceschini**
- [x] fix notes store with new backend changes
- [x] clean up space files

### CODE REVIEW

File: apps/frontend/src/components/Inbox/InboxExpandedItem.tsx [hunk 1]
```diff
@@ -22,18 +22,18 @@ export const InboxExpandedItem: React.FC = () => {
     description: "",
   })
 
-  const { selectedItem, setSelectedItem, updateItem } = useInboxStore()
+  const { item, setItem, mutateItem } = useCycleItemStore()
```
Comment (madhav-relish) [inline apps/frontend/src/components/Inbox/InboxExpandedItem.tsx]: Getting this

image

File: apps/frontend/src/components/Inbox/InboxExpandedItem.tsx [hunk 2]
```diff
@@ -22,18 +22,18 @@ export const InboxExpandedItem: React.FC = () => {
...
+    if (item) {
+      setEditItemId(item._id || "")
       setEditedItem({
-        title: selectedItem.title || "",
-        description: selectedItem.description || "",
+        title: item.title || "",
+        description: item.description || "",
       })
     }
     console.log(editedItem)
```
Comment (madhav-relish) [inline apps/frontend/src/components/Inbox/InboxExpandedItem.tsx]: Can be removed

File: apps/frontend/src/lib/store/cycle.store.ts [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+        }
+      )
+      console.log("API response:", data)
+      cycleItems_ = data.response
+      console.log("Setting cycleItems in store:", cycleItems_)
+      set({ cycleItems: cycleItems_, isFetched: true })
+      console.log("Store state after update:", get())
+    } catch (error) {
+      console.error("Error fetching cycle items: ", error)
+    } finally {
```
Comment (madhav-relish) [inline apps/frontend/src/lib/store/cycle.store.ts]: From now on it will be better if we start doing better error handling, like if the user token has expired, in that case api returns 401. So we can redirect them to login page and display a message that they've been logged out.

Need to put this check to most of the api calls not just talking about this PR. Maybe we can create a separate issue for this.

Comment (madhav-relish) [reply apps/frontend/src/lib/store/cycle.store.ts]: Otherwise the user will keep editing and their progress can get lost since the apis kept failing and the user never came to know

**Review by madhav-relish — CHANGES_REQUESTED** [review]
Adding a placeholder for description would be good, since as a user I have no idea where to click to add a description

image

File: apps/frontend/src/lib/store/cycle.store.ts (hunk 3 above)
Comment (joaorceschini) [reply apps/frontend/src/lib/store/cycle.store.ts]: you are right, lets create a issue for this then.
